management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true


resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100
  instances:
    bankService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2
  instances:
    bankService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1


resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 300
      retryExceptions:
        - io.github.resilience4j.bulkhead.BulkheadFullException
      ignoreExceptions:
        - com.tiarebalbi.resilience.retry.BankTransactionException
  instances:
    bankService:
      maxRetryAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - com.tiarebalbi.resilience.retry.BankTransactionException

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
  instances:
    stockAPI:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
      timeoutDuration: 50
      registerHealthIndicator: true
      subscribeForEvents: true


server:
  error:
    include-stacktrace: on_trace_param
  port: 9080

logging:
  level:
    org:
      springframework: debug