/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tiarebalbi.resilience

import com.tiarebalbi.resilience.circuitbreaker.CircuitBreakerDemo

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

suspend fun main(args: Array<String>) {
    // Circuit Breaker Demo
    CircuitBreakerDemo().run()

}
